### ISSUE TITLE
[MEDIUM] - Build a signin / signup / logout system

### ISSUE THREAD

**Issue by ibbatta** [ibbatta/node-express-server#18]
I am trying to build a signin / signup (and logout) system for my BE, with jwt and express-session, could someone help me to build it in the right way? 

---
FOLLOW THE **[HOW TO CONTRIBUTE](https://github.com/ibbatta/node-express-server#contributing)** PARAGRAPH FOR THE PULL REQUESTS

Please, leave a ⭐️ to support the project.

**Comment by gagandeepp** [comment]
interested

**Comment by ibbatta** [comment]
@gagandeepp you are welcome

**Comment by gagandeepp** [comment]
You have already added code for Signup and signin in User controller. What do you want me to do ?

**Comment by gagandeepp** [comment]
@ibbatta You have already added code for signin and signup . What do you want me to do?

**Comment by ibbatta** [comment]
@gagandeepp Yes, I've code a bit this Friday but the login/registration system is not complete. Actually I use JWT for everything and this is not the best practice (i was following the `first do it, then do it right, then do it better` philosophy).

I should split JWT and SESSION / COOKIE for the auth api requests and the user login session (or maybe there were others best practices)
