### ISSUE TITLE
[EASY] - Error handling (the right way)

### ISSUE THREAD

**Issue by ibbatta** [ibbatta/node-express-server#19]
How can I implement a custom error handler? And how is the right way to handle errors thrown by routes if the code is splitted in middleware, controller and routes?

---
FOLLOW THE **[HOW TO CONTRIBUTE](https://github.com/ibbatta/node-express-server#contributing)** PARAGRAPH FOR THE PULL REQUESTS

Please, leave a ⭐️ to support the project.

**Comment by odude102** [comment]
Can you provide some more detail? What errors do you want to handle?
