### ISSUE TITLE
Check the project and improve my code

### ISSUE THREAD

**Issue by ibbatta** [ibbatta/node-express-server#4]
For this `#hacktoberfest` event I am looking for someone who help me checking the code and helping me with these tasks:

- [x] check the server file and, in case, apply a refactory for "good practices" and performance

Feel free to open everything you want to grab the t-shirt (I will accept only useful pr)
_(please also support me ---> click on the :star: and I will love you more <3)_

---
FOLLOW THE **HOW TO CONTRIBUTE** PARAGRAPH FOR THE PULL REQUESTS

**Comment by Lol3rrr** [comment]
Hey i can take a look at some of it, not an expert myself but still

**Comment by ibbatta** [comment]
> Hey i can take a look at some of it, not an expert myself but still.
> Should i then just edit it?

@Lol3rrr sure dude!
