### ISSUE TITLE
[EASY] - Help me to improve my README.md

### ISSUE THREAD

**Issue by ibbatta** [ibbatta/node-express-server#5]
For this `#hacktoberfest` event I am looking for someone who helps me writing a good english readme, following these tasks:

- [ ] MAIN DESCRIPTION (based on following purposes):
This repo is a personal project made mainly for study and practice
My first goal is to create a microservice server that expose simple api (see auth route)
My final goal is to create a "look-like" wordpress in node, without a front end part, just exposing api

- [ ] FURTHER TASKS DESCRIPTION (based on following purposes):
Follow the "todo" section inside the readme to write a basic description for the next steps 

Feel free to open everything you want to grab the t-shirt (I will accept only useful pr)
_(please also support me ---> click on the :star: and I will love you more <3)_

---
FOLLOW THE **HOW TO CONTRIBUTE** PARAGRAPH FOR THE PULL REQUESTS

**Comment by fllprbt** [comment]
Please define good :). Are you talking in terms of expressiveness, presentation or what.. ^^
